# Change these first
owner: 7hanw1n # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
skipDeleteIssues: true
assignees:
  - 7hanw1n

sites:
  - name: mtw
    url: $MTW
  - name: SG
    url: $SG
  - name: FW
    url: $FW
    __dangerous__insecure: true
  - name: BKCS
    url: $BKCS
    __dangerous__insecure: true
    expectedStatusCodes:
     - 200
     - 403
     - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Status**"
  introMessage: **Status** page which uses **real-time** data from our [GitHub repository](https://github.com/7hanq1n/upptime).
  navbar:
    - title: Status
      href: /uptime

commitMessages:
  commitAuthorName: "7w1n"
  commitAuthorEmail: "7hanw1n@gmail.com"

i18n:
  footer: This page is [open source]($REPO)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
